### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by sjlagasse** [sfb-git/codecademy#1]
You didn't upload your entire project to Github. None of your image files are on your repo and so they don't load when I view your page. Also, your routing is different so your CSS import statement didn't work initially.

**Comment by sfb-git** [comment]
Thanks so much for the review.  I apologize...the course units for #1 & #2 did not go through how to use git or git commands, so I didn't know how to add the files on Github.  I used what I just learned in unit #3 to do a git push for all the files.  Thanks again.
