### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by sjlagasse** [sfb-git/codecademy#4]
Code wise, your project looks great. Your HTML file is spot on for the most part. You used a lot of elements, good indention, and had alt tags for you images. Make sure to remember to use wrapping divs. Your CSS was perfect. Great use of styles, adding styles to elements and keeping your code DRY (Don't Repeat Yourself). It seems like you messed up a bit when uploading to Github. Make sure to go over those steps so that you include all of your files. Other than that, good work.

**Comment by sfb-git** [comment]
I have updated the files based on your suggestions.  Not sure if you needed to review it again.  Thanks again.
